(370) Move the new note form onto its own page
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #102
Opened 2022-08-09 13:10 UTC by jkempster34

Currently, the new note form is underneath the project summary and subnavigation. This means that the error summary sits halfway down the page, whereas the GOV.UK guidance says it should sit at the top.

After a chat with our interaction designer, we have decided to move the new note form onto its own page. This solves the error message issue, and has an additional benefit that editing messages will be easier if we choose to implement that in the future.

This includes a few style updates:
- Add a cancel link to the new note form
- Rename the textarea label from "Notes" to "Enter note"
- Change the notes form submission button from "Add note" to "Save note"
- Remove the top separator of the list of notes

## Screenshots
![image](https://user-images.githubusercontent.com/47089130/183902874-9edc7b4e-99aa-42e4-9036-cc12fdceca51.png)
![image](https://user-images.githubusercontent.com/47089130/183902983-89410a25-2d81-4319-96a0-2bfe1fb02832.png)
![image](https://user-images.githubusercontent.com/47089130/183903107-6f2e7842-8dfc-4865-8114-3b8a0c51b280.png)

## Checklist

- [x] Attach this pull request to the appropriate card in Trello.
- [x] Update the `CHANGELOG.md` if needed.

2022-08-09 13:34 UTC, jkempster34 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Improve the error summary for the new note form](https://trello.com/c/mTiHWyTS/370-improve-the-error-summary-for-the-new-note-form)

2022-08-10 10:02 UTC, jacksonj04 requested changes
Couple of tiny picky bits; substance of the change looks sound to me :shipit:

2022-08-10 10:02 UTC, jacksonj04 commented on app/views/notes/_notes.html.erb
>    <h3 class="govuk-heading-m"><%= t("note.index.no_notes_yet") %></h3>
This doesn't feel quite right as a header now that there isn't a form on the page. Maybe an [inset text](https://design-system.service.gov.uk/components/inset-text/) above the "add form" button would be cleaner?

2022-08-10 12:58 UTC, jacksonj04 approved these changes
:shipit:

2022-08-10 13:53 UTC, merged