(678) Email team leads on project create
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #247
Opened 2022-10-13 16:30 UTC by jkempster34

## Changes

> WIP 🚨 ⚠️ 

To do:
- Check where we want to store our Notify API key.If its Rails creds, I'll need to share the master key
- Maybe update docs for how to send emails in dev.

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2022-10-17 13:49 UTC, jkempster34 commented
![](https://github.trello.services/images/mini-trello-icon.png) [System can send an email notification](https://trello.com/c/LbDgPRaa/678-system-can-send-an-email-notification)

2022-10-17 15:04 UTC, mec requested changes
This is looking great! It's very cool we can get so much value out of so little change! 

I could approve this - but I am interested in your thoughts on my comments so I am setting request changes.

2022-10-17 15:04 UTC, mec commented on app/mailers/team_leader_mailer.rb
> +      "ea4f72e4-f5bb-4b1a-b5f9-a94cc1840353",
Hmm, will all the template IDs get unwieldly as we add more? Should they be environment variables?

2022-10-17 15:06 UTC, jkempster34 commented on Gemfile.lock
> -    sidekiq (6.5.5)
It was just a deprecation warning filling up my terminal 

```
Passing the timeout as a positional argument is deprecated, it should be passed as a keyword argument sidekiq
```

2022-10-17 15:35 UTC, jkempster34 commented on app/controllers/projects_controller.rb
> +  private def notify_team_leaders
I reckon the TaskListCreator should be responsible for generating the task list only. If you look at the TaskListCreator, its currently far more complicated that the ProjectsController.

2022-10-18 07:52 UTC, mec commented on app/controllers/projects_controller.rb
> +  private def notify_team_leaders
Keeping controllers thin and the complexity out is, generally speaking, a good thing. I agree the TaskListCreator is getting bloated, but it is responsible for creating a new task list and that is the point at which the email is sent.

One benefit of not having this in the controller is that it should make testing it simpler.

Happy to keep this and see where we go once more notification come along.

2022-10-18 07:52 UTC, mec commented on app/mailers/team_leader_mailer.rb
> +      "ea4f72e4-f5bb-4b1a-b5f9-a94cc1840353",
I think this is good, just thinking ahead and about how best to handle these IDs, this one is encapsulated in the `TeamLeaderMailer` which I like, but I can see this coming apart when we have to send to multiple roles...

However we tackle this one sets the tone for those that follow (in my experience) so this is our chance to lay some best practice foundaitons.

2022-10-18 07:53 UTC, mec approved these changes
🚢

2022-10-18 09:50 UTC, merged