Feature/712 trust sharepoint link
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #260
Opened 2022-10-19 13:31 UTC by jkempster34

## Changes
### Add trust SharePoint link to Project
The two main entities involved in a conversion are the School and the Trust it
is joining. We already collect the school SharePoint folder link, we should do
the same for the Trust.

### Collect trust SharePoint link on project creation
We want to collect the trust SharePoint link when the user creates a project.

This includes some minor changes to the validation messages for a school
SharePoint link, so that they can be distinguished from the new trust
SharePoint link.

### Add the trust SharePoint link to the project information tab
This also changes "link" to "folder" for the school SharePoint folder, so that
the description matches the header.

### Add the trust SharePoint link to the project summary
This also changes "link" to "folder" for the school SharePoint folder, so that
the description matches the header.

## Screenshots
![image](https://user-images.githubusercontent.com/47089130/196705445-b7da9f2c-4905-4db7-a2fb-3a639eec13d3.png)

![image](https://user-images.githubusercontent.com/47089130/196705044-3782429b-3d10-4864-a5b7-4e9269f364a0.png)

## Checklist

- [x] Attach this pull request to the appropriate card in Trello.
- [x] Update the `CHANGELOG.md` if needed.

2022-10-19 13:32 UTC, jkempster34 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add trust SharePoint link to Project](https://trello.com/c/Iah5qLCh/712-add-trust-sharepoint-link-to-project)

2022-10-21 09:47 UTC, jacksonj04 requested changes
One smol copy/paste to fix, otherwise looks good to me!

2022-10-21 09:47 UTC, jacksonj04 commented on spec/models/project_spec.rb
> +      it { is_expected.to validate_presence_of :establishment_sharepoint_link }
Quick copy/paste snafu:

```suggestion
      it { is_expected.to validate_presence_of :trust_sharepoint_link }
```

2022-10-24 09:09 UTC, jacksonj04 approved these changes
![ship-let-the-ship-begin](https://user-images.githubusercontent.com/619082/197490675-3be61a9d-a04a-422d-bfb8-3069b7bdccbd.gif)

2022-10-24 09:09 UTC, merged