(168) Implement permission control for resources
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #44
Opened 2022-07-07 12:31 UTC by jacksonj04

We should appropriately control who has access to which resources and functionality

## Acceptance

- [x] Users have a concept of 'lead' (99e13bfa26249b39312d03a955869f60fc7b391e)
- [x] A user who is not a team lead can only view the projects on which they are the assigned DO
- [x] A user who is not a lead cannot assign or reassign a project
- [x] A user who is not a lead cannot create a new project
- [x] A user who is a lead can view all projects, even if not assigned
- [x] A user who is a lead can assign or reassign a project
- [x] A user who is a lead can create a new project

2022-07-08 13:41 UTC, jkempster34 commented on app/policies/project_policy.rb
> +    attr_reader :user, :scope
I thought this class with the nesting and private accessors was a bit odd, but I can see Pundit expects it like this. Interesting!

2022-07-08 15:02 UTC, mec requested changes
Love this - love Pundit! ❤️ 

I am not convinced we should restrict viewing non-assigned Projects just yet.

I would like to see more desciptive names in the specs e.g. `delivery_officer` instead of `user_1` - my reasoning being it makes the tests more approachable to developers who come along later and hear the humans speak the words but then it is not in the code.

@jkempster34 This work raises a really interesting thing I think it would be good to talk over as a dev team, so worth a look:

I know we mentioned this in Slack, we are reaching for feature specs a lot - which is cool, but they are our slowest test. I would lke to have a talk about this and how we think about our test suite.

I would also love to hear views on organising the specs, I've experienced this before where we have these different user roles, who have different experiences in the applcaiton, how we organise the specs could really help keep things approachable and concise - I am thinking mostly about feature specs as those are about our users, rather than our models.

I say all this becuase I beleive the foundation we lay now will be the patterns we follow, so its good to have conversations early!

2022-07-11 08:36 UTC, jacksonj04 commented on app/models/user.rb
> +    team_leader
TIL

2022-07-11 13:00 UTC, mec approved these changes

2022-07-11 13:45 UTC, merged