Feature/support email
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #442
Opened 2023-01-06 15:39 UTC by lozette

## Changes

_Add a summary of the changes in this pull request_

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-01-06 15:48 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change email support email address](https://trello.com/c/plnRSrK7/1010-change-email-address-in-error-messages-to-regionalservicesrgeducationgovuk)

2023-01-09 08:55 UTC, titlescreen requested changes
It looks like the content on the Page not found, API client timeout and Internal Server error pages still need the content updating. I had a quick look at changing this and the link but couldn't figure it out. Happy to have a go if you can show me how to amend one of them.

API time out content
![image](https://user-images.githubusercontent.com/13239597/211270826-2f8b7311-c7ed-4e69-b75a-82b20e4b49a2.png)

Page not found content
![image](https://user-images.githubusercontent.com/13239597/211270896-b9c8f58c-0d6f-440d-89a4-ea99934f3c44.png)

Internal server error content
![image](https://user-images.githubusercontent.com/13239597/211270959-f947d566-5ca3-4320-abd1-d5d810c8bdb6.png)

2023-01-09 10:51 UTC, titlescreen commented
Fixed a couple of small typos in the yml file.
Looks good but on my machine it still displays and uses the old email address. Not sure if I need to do some local db thing…

It uses the email [complete.rsd@education.gov.uk](mailto:complete.rsd@education.gov.uk?subject=Complete%20conversions%2C%20transfers%20and%20changes%3A%20support%20query) and I was expecting it to use [regionalservices.rg@education.gov.uk](mailto:regionalservices.rg@education.gov.uk?subject=Complete%20conversions%2C%20transfers%20and%20changes%3A%20support%20query)

![image](https://user-images.githubusercontent.com/13239597/211291273-e6e60045-1dd1-451f-b7ce-1a88767a22bd.png)

2023-01-09 11:44 UTC, titlescreen approved these changes
@lozette told me to restart the server locally and the email has updated. 

Looks good to me

2023-01-09 11:45 UTC, merged