(194) View and update actions
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #62
Opened 2022-07-20 13:27 UTC by jkempster34

https://trello.com/c/CsNfWkNp

### Show a checklist of Actions on the individual Task page
Initially, we want to show our YAML Actions as a completable checklist on each individual Task page.

### DRY up relationships in existing factories
We can simply use the name of the related factory when declaring relationships in FactoryBot.

### Add update action to Task controller
Users need to be able to complete Actions, and for this to be persisted.

2022-07-20 13:27 UTC, jkempster34 commented
![](https://github.trello.services/images/mini-trello-icon.png) [View and update a Tasks Actions](https://trello.com/c/CsNfWkNp/194-view-and-update-a-tasks-actions)

2022-07-21 08:47 UTC, mec commented
I started to review this and realised that @jacksonj04 is already doing one, so I will stop now.

2022-07-21 09:23 UTC, jacksonj04 requested changes
A couple of little tweaks, along with the stuff we chatted about in Slack.

I also think we could do with adding a 'back' link to the task page.

2022-07-21 12:56 UTC, jacksonj04 approved these changes

2022-07-21 12:58 UTC, merged