Bare bones API client for the Members API
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #641
Opened 2023-04-11 11:20 UTC by lozette

We are going to use the Members API at https://members-api.parliament.uk/ to fetch information about Members of Parliament. Add a very basic API client to call this API.

## Changes

_Add a summary of the changes in this pull request_

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-04-12 15:23 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fetch MP details from the members API](https://trello.com/c/sCIdfDJm/1427-fetch-mp-details-from-the-members-api)

2023-04-13 11:26 UTC, mec requested changes
Couple of comments in there, looks like a solid start though! 👍

2023-04-13 13:15 UTC, lozette commented on app/models/members_api/client.rb
> +      Result.new(nil, Error.new(I18n.t("members_api.errors.multiple", search_term: search_term)))
Yes, oops!

2023-04-13 13:58 UTC, lozette commented on app/models/base_api_model.rb
> +class BaseApiModel
It's made this commit hyooooge but it's done

2023-04-14 08:18 UTC, mec approved these changes

2023-04-14 08:27 UTC, merged