(195) Project tabs
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #69
Opened 2022-07-22 14:45 UTC by jkempster34

### Add project subnavigation tabs
We want to use the GOV.UK tab component to navigate between the project task list page and the project information page.

This adds partials to build the tab component, as well as a basic controller and view for the new project information page.

### Include authentication on the TasksController

2022-07-22 14:51 UTC, jkempster34 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Project Information to Project view](https://trello.com/c/VS0BOMTz/195-add-project-information-to-project-view)

2022-07-25 10:39 UTC, jacksonj04 requested changes
A little routing tweak I think to make the paths more intuitive, but otherwise looking good!

2022-07-25 10:39 UTC, jacksonj04 commented on config/routes.rb
> +  resources :project_information
I think this would be better as `/project/information` rather than `/project_information`.

2022-07-25 14:14 UTC, jacksonj04 commented on config/routes.rb
> +  resources :project_information, path: "/projects/information"
Should this be a child of the projects resource, so we get `projects/{id}/information"`?

2022-07-25 14:35 UTC, jacksonj04 approved these changes

2022-07-25 14:36 UTC, merged