Display local authorities and their details
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #693
Opened 2023-05-03 15:14 UTC by beeLorna

We are displaying the local authorities as there will be a requirement from a service support role to be able to add, edit and delete any local authorities within the service.

This is just the first stage in getting the local authority data up and displayed. Next will introduce the service support role and set access permissions the create, update and delete methods.

## Changes

_Add a summary of the changes in this pull request_

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-05-10 07:27 UTC, mec approved these changes
🚢 I am assuming we are adding a role and policy to control this next?

2023-05-10 07:27 UTC, mec commented on app/models/local_authority.rb
> +  validates :code, uniqueness: true
👍

2023-05-10 08:37 UTC, lozette commented
@mec Yes, I was going to add it all in one PR, I didn't realise it wasn't a draft PR 😮‍💨 

I'll request a re-review when I've added it

2023-05-11 09:09 UTC, mec requested changes

2023-05-11 09:09 UTC, mec commented on db/schema.rb
> +    t.boolean "service_support"
Does it makes sense for this to be false by default?

2023-05-11 09:53 UTC, mec approved these changes
🚢

2023-05-11 10:01 UTC, merged