Users can provide the new Academy URN
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #695
Opened 2023-05-04 12:00 UTC by lozette

## Changes

### Users can edit the Academy URN

Users can now edit a project to add an Academy URN. 

From the "All conversions without an academy URN" page (`/projects/all/new`) they can click on a link to add the Academy URN. This brings them to a form where they can enter the Academy URN.

<img width="1033" alt="Screenshot 2023-05-04 at 14 42 06" src="https://user-images.githubusercontent.com/1089521/236226492-740582b8-d326-4833-aac0-b5c9a5211f5a.png">

If they do not enter anything, they see an error message:

<img width="1142" alt="Screenshot 2023-05-04 at 14 43 35" src="https://user-images.githubusercontent.com/1089521/236226474-1001af4d-7875-4559-ad47-35ad9f9cb4fb.png">

If the Academy URN does not exist in GIAS, they see an error message:

<img width="1056" alt="Screenshot 2023-05-04 at 14 43 49" src="https://user-images.githubusercontent.com/1089521/236226471-0404f77c-53ba-47a3-a018-1a3e3678bf83.png">

If the Academy URN is found in GIAS, they see a confirmation message:

<img width="1106" alt="Screenshot 2023-05-04 at 14 43 15" src="https://user-images.githubusercontent.com/1089521/236226480-2f0a6860-948d-4eef-9311-a99695817ee9.png">

Upon confirmation, they are returned to the list page, with a success message:

<img width="1218" alt="Screenshot 2023-05-04 at 14 44 08" src="https://user-images.githubusercontent.com/1089521/236226464-16ccb203-f97f-431f-a52e-229e359bd7bd.png">

### New listing page

The "All conversions without an academy URN" now has a sister page featuring all projects with an academy URN. The two pages are linked by tabs.

<img width="1138" alt="Screenshot 2023-05-04 at 14 41 46" src="https://user-images.githubusercontent.com/1089521/236226460-9303a187-2bf7-4f03-bcc3-2598b2ca6421.png">

<img width="1124" alt="Screenshot 2023-05-04 at 14 41 55" src="https://user-images.githubusercontent.com/1089521/236226495-5450e286-95ef-42ec-99b3-9a153328c973.png">

## Checklist

- [x] Attach this pull request to the appropriate card in Trello.
- [x] Update the `CHANGELOG.md` if needed.

2023-05-04 13:57 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users can provide the new Academy URN](https://trello.com/c/APpvqMcC/1508-users-can-provide-the-new-academy-urn)

2023-05-05 08:08 UTC, mec commented
This is looking really nice! Couple of things I think from spinning it up:

- all views should be in a two-thirds column layout expect tables
- we should use the `urn_validator` on the urn entry form as you can add anything
- we need to add a permission for updating only the urn that the service support user can do without being assigned to the project - I don't think we have this `User` role yet (it is coming in the work Lorna has) so for now let any user update the `academy_urn`
- I am struggling a bit with the content, but I think perhaps we come back to that later?

2023-05-05 09:23 UTC, lozette commented
@mec Done the required amendments and fixed up the relevant commits 👍

2023-05-05 10:46 UTC, mec requested changes
Couple of small things. 

The content doesn't work well for me and I don't think for you either. Because this is a big feature that won't go infront of users just yet, I am inclined to ship the behaviour and get the content fix later - what do you think?

2023-05-05 10:46 UTC, mec commented on app/controllers/conversions/academy_urn_controller.rb
> +  def update
I think we need to give this a specific name so we can allow this update to happen when the user is not `assigned_to`, right now I can get stuck trying to update the academy urn for a project I am not assigned to - if we call this `update_academy_urn` or something, we can add a specific permission for it?

2023-05-05 10:46 UTC, mec commented on CHANGELOG.md
> +- Users can edit the Academy URN on a project
As these are primarily aimed at end users could we make this a bit more specific? Something like:

> User can provide the new academy urn once it has be created in Get information about schools

2023-05-05 10:46 UTC, mec commented on app/views/conversions/academy_urn/confirm.html.erb
> +<%= render partial: "projects/shared/signed_in_as", locals: {email_address: current_user.email} %>
We should really just delete this and stop propagating it!! Not something you should do here though!

2023-05-05 10:46 UTC, mec commented on app/views/projects/shared/_with_academy_urn_table.html.erb
> +  <table class="govuk-table" name="projects_table" aria-label="Projects table">
Please don't change this, but we do have the GOVUK view components, which includes tables: https://govuk-components.netlify.app/components/table/#input-erb-building-a-table-row-by-row

2023-05-09 08:52 UTC, mec approved these changes
🚢

2023-05-09 10:11 UTC, merged