Add project completion validation
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #761
Opened 2023-06-01 14:43 UTC by lozette

## Changes

A Project cannot be completed until All conditions have been met, the Grant payment certificate is received and the academy has opened. If the user tries to complete the project when these conditions are not met, they will see a message.

<img width="1152" alt="Screenshot 2023-06-01 at 15 45 14" src="https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/assets/1089521/291a0a9f-d46f-4fc2-8af5-8f993ddc106d">

## Checklist

- [x] Attach this pull request to the appropriate card in Trello.
- [x] Update the `CHANGELOG.md` if needed.

2023-06-01 15:01 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add project completion validation](https://trello.com/c/GXgeeOfv/1618-add-project-completion-validation)

2023-06-02 13:09 UTC, mec requested changes
Couple of small things -> Beautiful set of commits though - so clear! ❤️

2023-06-02 13:09 UTC, mec commented on config/locales/project.en.yml
> +      unable_to_complete: This project cannot be completed until all required conditions are met and the academy has opened.
I think we should state all the criteria like you have in the commit message, as a list.

2023-06-02 13:09 UTC, mec commented on CHANGELOG.md
> +- Do not allow a project to be completed until all conditions have been met and
We should mention the grant support certificate has been returned as well.

2023-06-02 13:09 UTC, mec commented on app/models/conversion/project.rb
> +    !conversion_date_provisional? && conversion_date.past?
I know this is super pedantic! 

Can we change this to `conversion_date_confirmed_and_passed?` or something - I am nervous about this whole 'has the school opened' thing and I would rather it was not baked into the code until we get a straight answer.

2023-06-07 07:28 UTC, mec approved these changes
🚢

2023-06-07 08:36 UTC, merged