Create a bare bones Transfer::Project and Transfer::TasksData
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #775
Opened 2023-06-07 11:14 UTC by lozette

Add a new Project type, Transfer::Project. It uses the ProjectPolicy.

Add a new Transfer::TasksData model, which uses a new table `transfer_task_lists` and the TaskListPolicy.

Add factories for the project and tasks data, and prove that new models can be created using them.

## Changes

_Add a summary of the changes in this pull request_

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-06-07 11:22 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add basic model for a Transfer](https://trello.com/c/xjOt9y6L/1568-add-basic-model-for-a-transfer)

2023-06-08 07:15 UTC, mec requested changes

2023-06-08 07:15 UTC, mec commented on db/migrate/20230607103526_create_transfer_tasks_data.rb
> +    create_table :transfer_task_lists, id: :uuid do |t|
Can the table be `transfer_tasks_data` then we don't need the table_name? We need to update the conversion one as well.

2023-06-08 08:53 UTC, mec approved these changes
🚢

2023-06-08 09:01 UTC, merged