Add a BOM to the CSV file to enforce UTF-8
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #806
Opened 2023-06-22 10:45 UTC by lozette

## Changes

The CSV was not displaying correctly in MS Excel, due to UTF-8 encoding not being enforce. Enforce UTF-8 via a BOM prepended to the CSV data.

<img width="594" alt="Screenshot 2023-06-22 at 11 33 08" src="https://github.com/DFE-Digital/dfe-complete-conversions-transfers-and-changes/assets/1089521/e17287f1-4ed4-453b-9818-2a6400480df6">

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-06-22 10:49 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Help Excel handle special characters in funding agreement letter export: The BOM](https://trello.com/c/wunKigRJ/1761-help-excel-handle-special-characters-in-funding-agreement-letter-export-the-bom)

2023-06-23 07:55 UTC, mec requested changes

2023-06-23 07:55 UTC, mec commented on app/controllers/all/opening/projects_controller.rb
> +    send_data "\uFEFF" + @csv, filename: "opening_#{month}_#{year}.csv", type: :csv, disposition: "attachment"
Are we able to but this in a method in the `OpeningProjectsCsvExporter`? It feels a little icky here, it's so unclear what it is doing, wrapping it in a helpfully named method would help a lot.

2023-06-23 07:55 UTC, mec commented on CHANGELOG.md
> +- Enforce UTF-8 encoding in the CSV download via a BOM (byte order mark)
I don't think we are enforcing UTF-8 - but we should! It probably happens inside `OpeningProjectsCsvExporter`: `CSV.generate`

2023-06-26 08:00 UTC, mec approved these changes
🚢

2023-06-26 09:25 UTC, merged