Feature/1757 add final columns to the funding agreement letters export
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #807
Opened 2023-06-22 14:47 UTC by lozette

## Changes

_Add a summary of the changes in this pull request_

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-06-23 11:12 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add final columns to the funding agreement letters export](https://trello.com/c/0hLXLFcs/1757-add-final-columns-to-the-funding-agreement-letters-export)

2023-06-26 08:03 UTC, mec requested changes

2023-06-26 08:03 UTC, mec commented on app/services/opening_projects_csv_exporter.rb
> +  private def format_date(date)
Is it worth putting this date format into the config and using `to_formatted_s(:csv_export)`?

2023-06-26 09:59 UTC, mec approved these changes
🚢

2023-06-26 10:38 UTC, merged