Add handed over view to team projects
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #884
Opened 2023-07-18 16:53 UTC by beeLorna

## Changes

This work adds in a `Handed over` view to the Team projects area which displays the projects that have been handed over to the Regional casework services team.
Each regional team can view this `Handed over` view and will see all their handed over regional projects.
The view is restricted to the Regional casework services team who won't see the `Handed over` tab.

## Checklist

- [x] Attach this pull request to the appropriate card in Trello.
- [x] Update the `CHANGELOG.md` if needed.

2023-07-18 16:54 UTC, beeLorna commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add handed over view to Team projects](https://trello.com/c/2VfBfLp8/1905-add-handed-over-view-to-team-projects)

2023-07-25 12:42 UTC, mec requested changes
Not you fault as it came later, but could you add the prefetcher and then this is good to go!

2023-07-25 12:42 UTC, mec commented on app/controllers/team/projects_controller.rb
> +    @pager, @projects = pagy_array(ByRegionProjectFetcherService.new.regional_casework_services_projects(@current_users_team))
Now that it is available, could you call the new `AcademiesApiPreFetcherService` here to make this view feel responsive:

`AcademiesApiPreFetcherService.new.call!(@projects)`

This is the pattern we use now anytime we have a paged view of projects.

2023-07-25 12:42 UTC, mec commented on app/controllers/team/projects_controller.rb
> +      return head(:not_found)
I've not seen this `head` before, something about this makes me wonder if there was another approach, but this works - so let's use it.

2023-07-25 14:27 UTC, mec approved these changes

2023-07-25 14:28 UTC, merged