Store when a user last created a session
DFE-Digital/dfe-complete-conversions-transfers-and-changes pull request #964
Opened 2023-08-07 10:40 UTC by lozette

## Changes

When a user logs in (creates a session), store a DateTime in the `latest_session` column on the user. This value will update each time a user creates a session.

## Checklist

- [ ] Attach this pull request to the appropriate card in Trello.
- [ ] Update the `CHANGELOG.md` if needed.

2023-08-07 10:42 UTC, lozette commented
![](https://github.trello.services/images/mini-trello-icon.png) [Record the last sign in datetime for each session.](https://trello.com/c/JA7zkZKh/1890-record-the-last-sign-in-datetime-for-each-session)

2023-08-08 09:20 UTC, mec requested changes
Could we show the last session date and time on the users table at `/users/active` - sorry it wasn't on the story!

2023-08-08 15:47 UTC, mec requested changes
Not so much a change, as an explination of those date arguments - no idea what those are?

2023-08-08 15:47 UTC, mec commented on spec/helpers/user_helper_spec.rb
> +        user = create(:user, latest_session: DateTime.new(2023, 0o1, 0o1, 10, 30, 0o0, 0))
What are those dates (`0o1`?)

2023-08-09 08:34 UTC, merged